# Project: Project1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Player.o GameMaps.o Events.o
LINKOBJ  = main.o Player.o GameMaps.o Events.o
LIBS     = -L"D:/Programas/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Programas/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Programas/Dev-Cpp/TDM-GCC-64/include" -I"D:/Programas/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Programas/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Programas/Dev-Cpp/TDM-GCC-64/include" -I"D:/Programas/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Programas/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Programas/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Programas\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Player.o: Player.cpp
	$(CPP) -c Player.cpp -o Player.o $(CXXFLAGS)

GameMaps.o: GameMaps.cpp
	$(CPP) -c GameMaps.cpp -o GameMaps.o $(CXXFLAGS)

Events.o: Events.cpp
	$(CPP) -c Events.cpp -o Events.o $(CXXFLAGS)
